services:
  postgres:
    image: postgres:16
    container_name: banking_postgres
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: banking_adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres