spring.application.name=banking-api
spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=${JWT_SECRET}

resend.api-key=${RESEND_API_KEY}
app.frontend-url=${FRONTEND_URL}
app.mail.from=Banking <noreply@mdiasgomes.com>

app.cookie.secure=${COOKIE_SECURE:false}
app.cookie.domain=${COOKIE_DOMAIN:}
app.cookie.same-site=${COOKIE_SAME_SITE:Lax}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
